name: 'Create new branch'

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        type: string
        default: 'dev'
      projectName:
        description: 'Project name'
        required: true
        type: string
        default: 'DEV branch project'
      addUserWithEmail:
        description: 'Add user with email'
        required: false
        type: string

jobs:
  createBranch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create temp dir
        run: | 
            mkdir temp
            chmod 777 temp
        
      - name: Create temp dir, create create project script without orgId
        if: "${{vars.CM_ORGANIZATION_ID == ''}}"
        run: | 
            cd temp
            echo -e "login\ncreateProject --title \"${{inputs.projectName}}\"\ndumpProject --skipData" > createProjectScript.txt
            cat createProjectScript.txt
            
      - name: Create temp dir, create create project script with orgId
        if: "${{vars.CM_ORGANIZATION_ID != ''}}"
        run: | 
            cd temp
            echo -e "login\ncreateProject --title \"${{inputs.projectName}}\" --organization ${{vars.CM_ORGANIZATION_ID}}\ndumpProject --skipData" > createProjectScript.txt
            cat createProjectScript.txt
            
      - name: Run docker CleverMaps Shell with create project script
        uses: addnab/docker-run-action@v3
        with:
          image: clevermaps/shell:latest
          options: --rm --name cm-shell --pull always --volume ${{ github.workspace }}/temp:/work:z -v ${{ github.workspace }}/temp/createProjectScript.txt:/createProjectScript.txt --env CM_ACCESS_TOKEN=${{ secrets.CM_ACCESS_TOKEN }} 
          run: java -jar "${HOME}/${can_shell_filename}" --cmdfile /createProjectScript.txt
          
      - name: Get projectId
        run: | 
            cd temp
            rm createProjectScript.txt
            echo "NEW_PROJECT_ID="$(ls)"" >> $GITHUB_ENV
            
      - name: Create new branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "refs/heads/${{env.NEW_PROJECT_ID}}/${{inputs.branchName}}"
          
      - name: Install jq
        if: "${{inputs.addUserWithEmail != ''}}"
        run: sudo apt-get install -y jq
        
      - name: Get bearer token
        if: "${{inputs.addUserWithEmail != ''}}"
        id: get-token
        run: |
          response=$(curl -X POST \
                     "https://secure.clevermaps.io/rest/oauth/token" \
                     -H "Content-Type: application/json" \
                     -H "Accept: application/json" \
                     -d '{"refresh_token": "'"${{ secrets.CM_ACCESS_TOKEN }}"'"}')
          echo ${response}
          echo "bearer_token="$(echo ${response} | jq '.access_token')"" >> $GITHUB_OUTPUT 
          echo "$bearer_token"
          
      - name: Invite user to project
        if: "${{ inputs.addUserWithEmail != '' }}"
        run: |
          # Prepare the invitation payload
          invitation_payload=$(jq -n \
            --arg email "${{ inputs.addUserWithEmail }}" \
            --arg role "ADMIN" \
            '{email: $email, role: $role}')

          echo "Payload:"
          echo "$invitation_payload"
          
          # Send the invitation request
          response=$(curl -X POST \
            "https://secure.clevermaps.io/rest/projects/${{ env.NEW_PROJECT_ID }}/invitations" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CM_ACCESS_TOKEN }}" \
            -d "$invitation_payload" -v)
          
          echo "Invitation response: $response"

    


   
    
            
            
            
