# This is a basic workflow to help you get started with Actions

name: Create new branch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        type: string
      projectName:
        description: 'Project name'
        required: false
        type: string
        default: 'DEV branch of project'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
