name: Create new branch

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        type: string
      projectName:
        description: 'Project name'
        required: true
        type: string
        default: 'DEV branch of project ...'
      addUserWithEmail:
        description: 'Add user with email'
        required: false
        type: string

jobs:
  createBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create temp dir, create create project script
        run: | 
            mkdir temp
            chmod 777 temp
            cd temp
            echo -e "login\ncreateProject --title ${INPUT_PROJECTNAME}\ndumpProject --skipData" > createProjectScript.txt
            cat createProjectScript.txt
