on:
  workflow_dispatch:
jobs:
  run_docker:
    name: run docker container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Show file content
        run: ls -a
      - name: Run docker CleverMaps
        uses: addnab/docker-run-action@v3
        with:
          image: clevermaps/shell:latest
          options: --rm --name cm-shell --pull always --volume ${{ github.workspace }}:/work:z --env CM_ACCESS_TOKEN=${{ secrets.ACCESSTOKEN }}
      
