name: 'Sync dev branch'

on:
  workflow_dispatch:

jobs:
  syncDev:
    if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create temp dir, create dump project script
        id: create-temp
        run: | 
            echo "CM_PROJECT_ID="${GITHUB_REF_NAME%%/*}"" >> $GITHUB_OUTPUT
            project_id="${GITHUB_REF_NAME%%/*}"
            mkdir temp
            chmod 777 temp
            cd temp
            echo -e "login\nopenProject --project ${project_id}\ndumpProject --skipData" > dumpscript.txt
            cat dumpscript.txt
            
      - name: Run docker CleverMaps Shell with dump script
        uses: addnab/docker-run-action@v3
        with:
          image: clevermaps/shell:beta
          options: --rm --name cm-shell --pull always --volume ${{ github.workspace }}/temp:/work:z -v ${{ github.workspace }}/temp/dumpscript.txt:/dumpscript.txt --env CM_ACCESS_TOKEN=${{ secrets.CM_ACCESS_TOKEN }} --user 1001:123
          run: java -jar "${HOME}/${can_shell_filename}" --cmdfile /dumpscript.txt 
          
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
                    
      - name: Run sync dev python script
        run: python .github/workflows/scripts/sync_dev.py ${{ github.workspace }}/metadata ${{ github.workspace }}/temp/${{steps.create-temp.outputs.CM_PROJECT_ID}}/metadata
      
      - name: Remove temp files
        run: |
          sudo rm -r temp
          sudo rm semicolon_delimited_script
      
      - name: Are changes present 
        id: changes_present
        run: |
          git status
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
        
      - name: Commit changes
        if: steps.changes_present.outputs.changed == 'true'
        run: |
          cur_date=`date +%Y-%m-%d:%T%Z`
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automatic synchronization commit of project on $cur_date"
          git push
