name: 'Update dev project'

on:
  workflow_dispatch:

  
jobs:
  update_project_pipeline:
    name: Update project pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create temp dir, create dump project script
        id: create-temp
        run: | 
            echo "CM_PROJECT_ID="${GITHUB_REF_NAME%%/*}"" >> $GITHUB_OUTPUT
            project_id="${GITHUB_REF_NAME%%/*}"
            mkdir temp
            chmod 777 temp
            cd temp
            echo -e "login\nopenProject --project ${project_id}\ndumpProject --skipData" > dumpscript.txt
            cat dumpscript.txt
            echo -e "login\nopenProject --project ${project_id}\nrestoreMetadata\npushProject --skipData" > loadscript.txt
            cat loadscript.txt
            
      - name: Run docker CleverMaps Shell with dump script
        uses: addnab/docker-run-action@v3
        with:
          image: clevermaps/shell:beta
          options: --rm --name cm-shell --pull always --volume ${{ github.workspace }}/temp:/work:z -v ${{ github.workspace }}/temp/dumpscript.txt:/dumpscript.txt --env CM_ACCESS_TOKEN=${{ secrets.CM_ACCESS_TOKEN }} --user 1001:123
          run: /usr/local/bin/docker-entrypoint.sh --cmdfile /dumpscript.txt
          
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Run replace content python script
        run: python .github/workflows/scripts/replace_content.py ${{ github.workspace }}/temp/${{steps.create-temp.outputs.CM_PROJECT_ID}}/metadata ${{ github.workspace }}/metadata
        
      - name: Run docker CleverMaps Shell with load script
        uses: addnab/docker-run-action@v3
        with:
          image: clevermaps/shell:beta
          options: --rm --name cm-shell --pull always --volume ${{ github.workspace }}/temp:/work:z -v ${{ github.workspace }}/temp/loadscript.txt:/loadscript.txt --env CM_ACCESS_TOKEN=${{ secrets.CM_ACCESS_TOKEN }} --user 1001:123
          run: /usr/local/bin/docker-entrypoint.sh --cmdfile /loadscript.txt
      
