on:
  workflow_dispatch:
jobs:
  run_docker:
    name: run docker container
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Create temp dir, create dump project script
        run: | 
            mkdir temp
            chmod 777 temp
            cd temp
            echo -e "login\nopenProject --project ${GITHUB_REF_NAME}\ndumpProject --skipData" > script.txt
            cat script.txt
      - name: Run docker CleverMaps
        uses: addnab/docker-run-action@v3
        with:
          image: clevermaps/shell:latest
          options: --rm --name cm-shell --pull always --volume ${{ github.workspace }}/temp:/work:z -v ${{ github.workspace }}/temp/script.txt:/script.txt --env CM_ACCESS_TOKEN=${{ secrets.ACCESSTOKEN }} 
          run: java -jar "${HOME}/${can_shell_filename}" --cmdfile /script.txt
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: run python
        run: python .github/workflows/replace_content.py ${{ github.workspace }}/temp/${GITHUB_REF_NAME} ${{ github.workspace }}/metadata
      
