on:
  workflow_dispatch:
jobs:
  run_docker:
    name: run docker container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Show file content
        run: | 
            ls -a 
            mkdir 'temp'
            cd temp
            ls
            echo "login \\n openProject --project ` ${{ env.GITHUB_REF_NAME }} | cut -d'/' -f1` \\n dumpProject --skipData" > script.txt
            cat script.txt
      - name: Show env variables
        run: env
      - name: Run docker CleverMaps
        uses: addnab/docker-run-action@v3
        with:
          image: clevermaps/shell:latest
          options: --rm -ti --name cm-shell --pull always --volume ${{ github.workspace }}/temp:/work:z -v /temp/script.txt:/script.txt / --env CM_ACCESS_TOKEN=${{ secrets.ACCESSTOKEN }} --cmdfile /script.txt
      
